CREATE TABLE CUST_CARD_TEMPLATE_FIELDS
(
  CUST_CARD_TEMPLATE_FIELD_OID  NUMBER(9),
  UPDATE_COUNT                  NUMBER(9),
  LAST_UPDATED_AT               DATE,
  LAST_UPDATED_BY               NVARCHAR2(30),
  CUSTOMER_CARD_TEMPLATE_OID    NUMBER(9),
  BULK_CARD_COLUMN_OID          NUMBER(9),
  VALUE                         NVARCHAR2(1000)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
