CREATE TABLE CUSTOMER_REPORT_LEVELS
(
  REPORT_LEVEL_OID  NUMBER(9),
  UPDATE_COUNT      NUMBER(9),
  LAST_UPDATED_AT   DATE,
  LAST_UPDATED_BY   NVARCHAR2(30),
  CONTACT_NAME      NVARCHAR2(100),
  CUSTOMER_MID      NUMBER(9),
  LEVEL_NUMBER      NUMBER(9),
  LEVEL_CODE        NVARCHAR2(3),
  DESCRIPTION       NVARCHAR2(200),
  ADDRESS_OID       NUMBER(9),
  CONTACT_TITLE     NVARCHAR2(30),
  EMAIL_ADDRESS     NVARCHAR2(100),
  PHONE_BUSINESS    NVARCHAR2(30),
  PHONE_FAX         NVARCHAR2(30),
  PHONE_MOBILE_1    NVARCHAR2(30),
  PHONE_MOBILE_2    NVARCHAR2(30)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
