CREATE TABLE CUSTOMER_PIN_GROUPS
(
  CUSTOMER_PIN_GROUP_OID  NUMBER(9),
  LAST_UPDATED_AT         DATE,
  LAST_UPDATED_BY         NVARCHAR2(30),
  UPDATE_COUNT            NUMBER(9),
  NAME                    NVARCHAR2(50),
  DESCRIPTION             NVARCHAR2(100),
  CUSTOMER_MID            NUMBER(9),
  ENCRYPTED_GROUP_PIN     NVARCHAR2(30)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
