CREATE TABLE CUSTOMER_WALLET_CARDS
(
  CUSTOMER_WALLET_CARD_OID  NUMBER(9),
  CUSTOMER_WALLET_OID       NUMBER(9),
  CARD_OID                  NUMBER(9),
  EFFECTIVE_ON              DATE,
  EXPIRES_ON                DATE,
  UPDATE_COUNT              NUMBER(9),
  LAST_UPDATED_AT           DATE,
  LAST_UPDATED_BY           NVARCHAR2(30)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
