CREATE TABLE CUSTOMER_PRODUCT_TOT_LOCS
(
  CUSTOMER_PROD_TOT_LOC_OID  NUMBER(9),
  UPDATE_COUNT               NUMBER(9),
  LAST_UPDATED_AT            DATE,
  LAST_UPDATED_BY            NVARCHAR2(30),
  CUSTOMER_MID               NUMBER(9),
  LOCATION_MID               NUMBER(9),
  PRODUCT_OID                NUMBER(9),
  TOTAL_CATEGORY_CID         NUMBER(9),
  MTD_QUANTITY               NUMBER(18,4)       DEFAULT 0,
  MTD_VALUE                  NUMBER(18,4)       DEFAULT 0,
  MTD_ORIGINAL_VALUE         NUMBER(18,4)       DEFAULT 0,
  MTD_TAX_VALUE              NUMBER(18,4)       DEFAULT 0,
  MTD_REBATE_VALUE           NUMBER(18,4)       DEFAULT 0,
  YTD_QUANTITY               NUMBER(18,4)       DEFAULT 0,
  YTD_VALUE                  NUMBER(18,4)       DEFAULT 0,
  YTD_ORIGINAL_VALUE         NUMBER(18,4)       DEFAULT 0,
  YTD_TAX_VALUE              NUMBER(18,4)       DEFAULT 0,
  YTD_REBATE_VALUE           NUMBER(18,4)       DEFAULT 0,
  LTD_QUANTITY               NUMBER(18,4)       DEFAULT 0,
  LTD_VALUE                  NUMBER(18,4)       DEFAULT 0,
  LTD_ORIGINAL_VALUE         NUMBER(18,4)       DEFAULT 0,
  LTD_TAX_VALUE              NUMBER(18,4)       DEFAULT 0,
  LTD_REBATE_VALUE           NUMBER(18,4)       DEFAULT 0,
  LMTH_QUANTITY              NUMBER(18,4)       DEFAULT 0,
  LMTH_VALUE                 NUMBER(18,4)       DEFAULT 0,
  LMTH_ORIGINAL_VALUE        NUMBER(18,4)       DEFAULT 0,
  LMTH_TAX_VALUE             NUMBER(18,4)       DEFAULT 0,
  LMTH_REBATE_VALUE          NUMBER(18,4)       DEFAULT 0,
  MTD_FEE_AMOUNT             NUMBER(18,4)       DEFAULT 0,
  MTD_FEE_TAX                NUMBER(18,4)       DEFAULT 0,
  YTD_FEE_AMOUNT             NUMBER(18,4)       DEFAULT 0,
  YTD_FEE_TAX                NUMBER(18,4)       DEFAULT 0,
  LTD_FEE_AMOUNT             NUMBER(18,4)       DEFAULT 0,
  LTD_FEE_TAX                NUMBER(18,4)       DEFAULT 0,
  LMTH_FEE_AMOUNT            NUMBER(18,4)       DEFAULT 0,
  LMTH_FEE_TAX               NUMBER(18,4)       DEFAULT 0,
  TRANS_REBATE_TYPE_CID      NUMBER(9)          DEFAULT 11601
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
