CREATE TABLE CUSTOMER_ACCNT_PROFILES
(
  CUSTOMER_ACCNT_PROFILE_OID   NUMBER(9),
  UPDATE_COUNT                 NUMBER(9),
  LAST_UPDATED_AT              DATE,
  LAST_UPDATED_BY              NVARCHAR2(30),
  CUSTOMER_MID                 NUMBER(9),
  ACCOUNT_CONTROL_PROFILE_OID  NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
