CREATE TABLE CUSTOMER_CARD_TEMPLATES
(
  CUSTOMER_CARD_TEMPLATE_OID  NUMBER(9),
  UPDATE_COUNT                NUMBER(9),
  LAST_UPDATED_AT             DATE,
  LAST_UPDATED_BY             NVARCHAR2(30),
  CUSTOMER_MID                NUMBER(9),
  BULK_CARD_TEMPLATE_OID      NUMBER(9),
  NAME                        NVARCHAR2(30),
  DESCRIPTION                 NVARCHAR2(1000),
  APPROVER_COMMENTS           NCLOB,
  APPROVER                    NVARCHAR2(30),
  FAILURE_REASON_CID          NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
