CREATE TABLE CUSTOMER_CHARSTIC_VALUES
(
  ENTITY_CHARSTIC_VALUE_OID  NUMBER(9),
  LAST_UPDATED_AT            DATE,
  LAST_UPDATED_BY            NVARCHAR2(30),
  UPDATE_COUNT               NUMBER(9),
  ENTITY_SPEC_CHARSTIC_OID   NUMBER(9),
  ENTITY_OID                 NUMBER(9),
  ENTITY_SPEC_OID            NUMBER(9),
  VALUE                      NVARCHAR2(256)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
