CREATE TABLE CUSTOMER_CARD_PROFILES
(
  CUSTOMER_CARD_PROFILE_OID  NUMBER(9),
  UPDATE_COUNT               NUMBER(9),
  LAST_UPDATED_AT            DATE,
  LAST_UPDATED_BY            NVARCHAR2(30),
  CUSTOMER_MID               NUMBER(9),
  CARD_CONTROL_PROFILE_OID   NUMBER(9),
  FEE_PROFILE_OID            NUMBER(9),
  CARD_OFFER_OID             NUMBER(9),
  CARD_PRODUCT_OID           NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
