CREATE TABLE CUSTOMER_WALLETS
(
  CUSTOMER_WALLET_OID          NUMBER(9),
  CUSTOMER_WALLET_DESCRIPTION  NVARCHAR2(30),
  CUSTOMER_MID                 NUMBER(9),
  CUSTOMER_WALLET_STATUS_CID   NUMBER(9),
  UPDATE_COUNT                 NUMBER(9),
  LAST_UPDATED_AT              DATE,
  LAST_UPDATED_BY              NVARCHAR2(30),
  CUSTOMER_WALLET_CODE         NVARCHAR2(30)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
