CREATE TABLE CUSTOMER_COST_CENTRES
(
  CUSTOMER_COST_CENTRE_OID   NUMBER(9),
  UPDATE_COUNT               NUMBER(9),
  LAST_UPDATED_AT            DATE,
  LAST_UPDATED_BY            NVARCHAR2(30),
  CUSTOMER_MID               NUMBER(9),
  CUSTOMER_COST_CENTRE_CODE  NVARCHAR2(30),
  DESCRIPTION                NVARCHAR2(100),
  SHORT_DESCRIPTION          NVARCHAR2(12)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
